fpl/urls.py
from django.urls import include, path

from fpl import views

app_name = 'fpl'

classic_league_patterns = ([
                               path('', views.ClassicLeagueListView.as_view(), name='list'),
                               path('<int:league_pk>/', views.ClassicLeagueDetailView.as_view(), name='detail'),
                               path('<int:league_pk>/process-payouts', views.ClassicLeagueRefreshView.as_view(),
                                    name='process-payouts')
                           ], 'classic')

head_to_head_league_patterns = ([
                                    path('', views.HeadToHeadLeagueListView.as_view(), name='list'),
                                    path('<int:league_pk>/', views.HeadToHeadLeagueDetailView.as_view(), name='detail'),
                                    path('<int:league_pk>/process-payouts', views.HeadToHeadLeagueRefreshView.as_view(),
                                         name='process-payouts')
                                ], 'head-to-head')

season_patterns = ([
                       path('', views.SeasonListView.as_view(), name='list'),
                       path('<int:season_pk>/', views.SeasonDetailView.as_view(), name='detail'),
                       path('<int:season_pk>/classic-leagues/', include(classic_league_patterns)),
                       path('<int:season_pk>/head-to-head-leagues/', include(head_to_head_league_patterns))
                   ], 'season')

urlpatterns = [
    path('seasons/', include(season_patterns))
]

leaguetracker/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fpl/', include('fpl.urls'))
]

leagues/models.py
from django.conf import settings
from django.db import models


class League(models.Model):
    season = models.ForeignKey('Season', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    entrants = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, through='LeagueEntrant')
    entry_fee = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    def __str__(self):
        return '({season}) - {name}'.format(season=self.season, name=self.name)


class LeagueEntrant(models.Model):
    entrant = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    paid_entry = models.BooleanField()

    def __str__(self):
        return '{league} - {entrant}'.format(
            league=self.league,
            entrant=self.entrant
        )

    class Meta:
        unique_together = ('entrant', 'league')


class Payout(models.Model):
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    position = models.IntegerField()
    start_date = models.DateField()
    end_date = models.DateField()
    winner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    paid_out = models.BooleanField()

    def calculate_winner(self):
        raise NotImplementedError

    def __str__(self):
        return '{league} - {name} Position {position} ({start_date}-{end_date}): {amount}'.format(
            league=self.league,
            name=self.name,
            position=self.position,
            start_date=self.start_date,
            end_date=self.end_date,
            amount=self.amount
        )

    class Meta:
        unique_together = ('league', 'position', 'start_date', 'end_date', 'winner')


class Season(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return '{start_date} - {end_date}'.format(
            start_date=self.start_date,
            end_date=self.end_date
        )

    class Meta:
        unique_together = ('start_date', 'end_date')

fpl/views.py
# Create your views here.
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView, RedirectView

from fpl.models import ClassicLeague, HeadToHeadLeague
from leagues.models import Season


class LeagueListView(ListView):

    def get_queryset(self):
        return self.model.objects.filter(league__season=self.kwargs['season_pk'])


class ClassicLeagueListView(LeagueListView):
    model = ClassicLeague
    context_object_name = 'league_list'
    template_name = 'fpl/league_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['league_type'] = 'Classic Leagues'
        context['base_url'] = 'fpl:season:classic:detail'
        season = Season.objects.get(pk=self.kwargs['season_pk'])
        context['navbar_levels'] = [
            {
                'name': 'Seasons',
                'href': reverse('fpl:season:list')
            },
            {
                'name': str(season),
                'href': reverse('fpl:season:detail', args=[season.pk])
            },
            {
                'name': 'Classic Leagues',
                'href': reverse('fpl:season:classic:list', args=[season.pk])
            }
        ]
        return context


class HeadToHeadLeagueListView(LeagueListView):
    model = HeadToHeadLeague
    context_object_name = 'league_list'
    template_name = 'fpl/league_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['league_type'] = 'Head To Head Leagues'
        context['base_url'] = 'fpl:season:head-to-head:detail'
        season = Season.objects.get(pk=self.kwargs['season_pk'])
        context['navbar_levels'] = [
            {
                'name': 'Seasons',
                'href': reverse('fpl:season:list')
            },
            {
                'name': str(season),
                'href': reverse('fpl:season:detail', args=[season.pk])
            },
            {
                'name': 'Head To Head Leagues',
                'href': reverse('fpl:season:head-to-head:list', args=[season.pk])
            }
        ]
        return context


class LeagueDetailView(DetailView):
    pk_url_kwarg = 'league_pk'


class ClassicLeagueDetailView(LeagueDetailView):
    model = ClassicLeague
    context_object_name = 'league'
    template_name = 'fpl/league_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['league_type'] = 'Classic League'
        context['base_url'] = 'fpl:season:classic:process-payouts'
        season = Season.objects.get(pk=self.kwargs['season_pk'])
        league = self.model.objects.get(pk=self.kwargs['league_pk'])
        context['navbar_levels'] = [
            {
                'name': 'Seasons',
                'href': reverse('fpl:season:list')
            },
            {
                'name': str(season),
                'href': reverse('fpl:season:detail', args=[season.pk])
            },
            {
                'name': 'Classic Leagues',
                'href': reverse('fpl:season:classic:list', args=[season.pk])
            },
            {
                'name': league.league.name,
                'href': reverse('fpl:season:classic:detail', args=[season.pk, league.pk])
            }
        ]

        return context


class HeadToHeadLeagueDetailView(LeagueDetailView):
    model = HeadToHeadLeague
    context_object_name = 'league'
    template_name = 'fpl/league_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['league_type'] = 'Head To Head League'
        context['base_url'] = 'fpl:season:head-to-head:process-payouts'
        season = Season.objects.get(pk=self.kwargs['season_pk'])
        league = self.model.objects.get(pk=self.kwargs['league_pk'])
        context['navbar_levels'] = [
            {
                'name': 'Seasons',
                'href': reverse('fpl:season:list')
            },
            {
                'name': str(season),
                'href': reverse('fpl:season:detail', args=[season.pk])
            },
            {
                'name': 'Head To Head Leagues',
                'href': reverse('fpl:season:head-to-head:list', args=[season.pk])
            },
            {
                'name': league.league.name,
                'href': reverse('fpl:season:head-to-head:detail', args=[season.pk, league.pk])
            }
        ]
        return context


class LeagueRefreshView(RedirectView):
    permanent = False
    http_method_names = ['post']
    league_type = None
    base_url = ''

    def get_redirect_url(self, *args, **kwargs):
        season_id = kwargs['season_pk']
        league_id = kwargs['league_pk']
        league = get_object_or_404(self.league_type, pk=league_id)
        last_updated = league.last_updated if league.last_updated else timezone.now() - timezone.timedelta(hours=2)
        if timezone.timedelta(hours=1) < timezone.now() - last_updated:
            league.process_payouts()
        return reverse(self.base_url, args=[season_id, league_id])


class ClassicLeagueRefreshView(LeagueRefreshView):
    league_type = ClassicLeague
    base_url = 'fpl:season:classic:detail'


class HeadToHeadLeagueRefreshView(LeagueRefreshView):
    league_type = HeadToHeadLeague
    base_url = 'fpl:season:head-to-head:detail'


class SeasonListView(ListView):
    model = Season
    context_object_name = 'season_list'
    template_name = 'fpl/season_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['base_url'] = 'fpl:season:detail'
        context['navbar_levels'] = [
            {
                'name': 'Seasons',
                'href': reverse('fpl:season:list')
            }
        ]
        return context


class SeasonDetailView(DetailView):
    model = Season
    context_object_name = 'season'
    template_name = 'fpl/season_detail.html'
    pk_url_kwarg = 'season_pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        season = kwargs['object']
        context['navbar_levels'] = [
            {
                'name': 'Seasons',
                'href': reverse('fpl:season:list')
            },
            {
                'name': str(season),
                'href': reverse('fpl:season:detail', args=[season.pk])
            }
        ]
        context['league_types'] = [
            {
                'name': 'Classic Leagues',
                'href': reverse('fpl:season:classic:list', args=[season.pk])
            },
            {
                'name': 'Head To Head Leagues',
                'href': reverse('fpl:season:head-to-head:list', args=[season.pk])
            },
        ]
        return context

templates/fpl/classicleague_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>Classic League: {{ classic_league.league.name }}</h2>
    <table>
        <thead>
        <tr>
            <th>Team</th>
            <th>Manager</th>
            <th>Entry Paid</th>
            <th>Score</th>
        </tr>
        </thead>
        <tbody>
        {% for manager in classic_league.managers %}
            <tr>

                <td>
                    <a href="https://fantasy.premierleague.com/a/team/{{ manager.fpl_manager_id }}">{{ manager.team_name }}</a>
                </td>
                <td>
                    {{ manager.entrant.first_name }} {{ manager.entrant.last_name }}
                </td>
                <td>{{ manager.paid_entry }}</td>
                <td>{{ manager.current_score }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <h3>Payouts: </h3>
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Amount</th>
            <th>Winner</th>
            <th>Paid Out</th>
        </tr>
        </thead>
        <tbody>
        {% for payout in classic_league.league.payout_set.all|dictsort:"position"|dictsort:"start_date"|dictsort:"name" %}
            <tr>
                <td>{{ payout.name }}</td>
                <td>{{ payout.position }}</td>
                <td>{{ payout.start_date }}</td>
                <td>{{ payout.end_date }}</td>
                <td>{{ payout.amount }}</td>
                <td>{{ payout.winner.first_name }} {{ payout.winner.last_name }}</td>
                <td>{{ payout.paid_out }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <h3>Last Updated: {{ classic_league.last_updated }}</h3>
    <form action="{% url 'fpl:classic-league:process-payouts' classic_league.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Refresh League Data and Process Payouts"/>
    </form>

{% endblock %}

templates/fpl/league_detail.html
{% extends 'base.html' %}

{% block content %}
    {% include 'fpl/navbar.html' %}
    <div class="container">
        <h2>{{ league_type }}: {{ league.league.name }}</h2>
        <h3>Standings</h3>
        <table class="table table-sm table-striped table-bordered table-hover">
            <thead class="thead-dark">
            <tr>
                <th>Team</th>
                <th>Manager</th>
                <th>Entry Paid</th>
                <th>Score</th>
                {% if league_type == 'Head To Head League' %}
                    <th>Head To Head Score</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for manager in league.managers %}
                <tr>

                    <td>
                        <a href="https://fantasy.premierleague.com/a/team/{{ manager.fpl_manager_id }}">{{ manager.team_name }}</a>
                    </td>
                    <td>
                        {{ manager.entrant.first_name }} {{ manager.entrant.last_name }}
                    </td>
                    <td>{{ manager.paid_entry }}</td>
                    <td>{{ manager.current_score }}</td>
                    {% if league_type == 'Head To Head League' %}
                        <td>{{ manager.current_h2h_score }}</td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <h3>Payouts</h3>
        <table class="table table-sm table-striped table-bordered table-hover">
            <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Amount</th>
                <th>Winner</th>
                <th>Paid Out</th>
            </tr>
            </thead>
            <tbody>
            {% for payout in league.league.payout_set.all|dictsort:"position"|dictsort:"start_date"|dictsort:"name" %}
                <tr>
                    <td>{{ payout.name }}</td>
                    <td>{{ payout.position }}</td>
                    <td>{{ payout.start_date }}</td>
                    <td>{{ payout.end_date }}</td>
                    <td>{{ payout.amount }}</td>
                    <td>{{ payout.winner.first_name }} {{ payout.winner.last_name }}</td>
                    <td>{{ payout.paid_out }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <h3 class="row justify-content-center">Last Updated: {{ league.last_updated }}</h3>
        <form action="{% url base_url league.league.season.pk league.pk %}" method="post" class="row justify-content-center">
            {% csrf_token %}
            <input type="submit" class="btn btn-outline-info" value="Refresh League Data and Process Payouts"/>
        </form>

    </div>
{% endblock %}

templates/fpl/league_list.html
{% extends 'base.html' %}

{% block content %}
    {% include 'fpl/navbar.html' %}
    <div class="container">
        <h2>{{ league_type }}</h2>
        <div class="list-group">
            {% for league in league_list %}
                <a href="{% url base_url league.league.season.pk league.pk %}" class="list-group-item list-group-item-action">
                    {{ league.league.name }}
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/fpl/navbar.html
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        {% for navbar_level in navbar_levels %}
            <li class="breadcrumb-item {% if forloop.last %}active{% endif %}">
                <a {% if not forloop.last %} href={{ navbar_level.href }} {% endif %}>{{ navbar_level.name }}</a>
            </li>
        {% endfor %}
    </ol>
</nav>

templates/fpl/season_detail.html
{% extends 'base.html' %}

{% block content %}
    {% include 'fpl/navbar.html' %}
    <div class="container">
        <h2>Seasons: {{ season }}</h2>
        <div class="list-group">
            {% for league_type in league_types %}
                <a href="{{ league_type.href }}" class="list-group-item list-group-item-action">
                    {{ league_type.name }}
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/fpl/season_list.html
{% extends 'base.html' %}

{% block content %}
    {% include 'fpl/navbar.html' %}
    <div class="container">
        <h2>Seasons</h2>
        <div class="list-group">
            {% for season in season_list %}
                <a href="{% url base_url season.pk %}" class="list-group-item list-group-item-action">
                    {{ season }}
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}